version: '3.7'
services:
  postgresql:
    image: postgres:12.0-alpine
    container_name: feupexchange_postgresql
    restart: always
    env_file:
      - postgresql/.env
    volumes:
      - postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: feupexchange_pgadmin
    env_file:
      - pgadmin/.env
    ports:
      - "5050:80"
    depends_on:
      - postgresql
    links:
      - postgresql

  django:
    build:
      context: ./django
      dockerfile: dockerfile_prod
    container_name: feupexchange_django
    command: gunicorn feup_exchange_backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/feupexchange/django/staticfiles
      - media_volume:/home/feupexchange/django/mediafiles
    expose:
      - 8000
    depends_on:
      - postgresql
    env_file:
      - django/.env.prod

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile_nginx
    container_name: feupexchange_nginx
    volumes:
      - static_volume:/home/feupexchange/django/staticfiles
      - media_volume:/home/feupexchange/django/mediafiles
    ports:
      - 8000:80
    depends_on:
      - django

volumes:
  postgres:
  static_volume:
  media_volume:
